# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hhe07/programming/ecen2350/hw_12/hw_12.srcs/sources_1/ip/xadc_pot/xadc_pot.xci
# IP: The module: 'xadc_pot' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hhe07/programming/ecen2350/hw_12/hw_12.gen/sources_1/ip/xadc_pot/xadc_pot_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pot'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hhe07/programming/ecen2350/hw_12/hw_12.gen/sources_1/ip/xadc_pot/xadc_pot.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pot'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hhe07/programming/ecen2350/hw_12/hw_12.srcs/sources_1/ip/xadc_pot/xadc_pot.xci
# IP: The module: 'xadc_pot' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hhe07/programming/ecen2350/hw_12/hw_12.gen/sources_1/ip/xadc_pot/xadc_pot_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pot'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hhe07/programming/ecen2350/hw_12/hw_12.gen/sources_1/ip/xadc_pot/xadc_pot.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pot'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
